language: ruby
rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.3
  - 2.6

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

addons:
  code_climate:
    repo_token: 84e47c3e41ba9fbc2d639c167be45aa3f6c077374015309dac005ab51f713d83

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - eturino@eturino.com
    on_failure: change
    on_success: never
